name: Build-Test-Deploy

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-Unit_testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - name: Install Dependencies
              run: npm install
            - name: Execute the unit tests
              run: npm run test:unit
            - name: Display Username
              run: echo 'baigeorgi'
    UI_tetsing:
        needs: build-and-Unit_testing
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - name: Install Dependencies
              run: npm install
            - name: Execute the UI tests
              run: npm run test:ui
