name: Build-Test-Deploy

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-Unit_testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - name: Install Dependencies
              run: npm install
            - name: Execute the unit tests
              run: npm run test:unit
            - name: Display Username
              run: echo 'baigeorgi'
    UI_tetsing:
        needs: build-and-Unit_testing
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - name: Install Dependencies
              run: npm install
            - name: Install Playwright
              run: npx playwright install
            - name: Start the app
              run: npm start &
            - name: Execute the UI tests
              run: npm run test:ui
    deploy:
        needs: UI_tetsing
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to production
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                  service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
                  api-key: ${{ secrets.MY_RENDER_API_KEY }}
